# Generated by Django 4.1 on 2022-08-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='novo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Part', models.CharField(max_length=150)),
                ('Code', models.CharField(max_length=150)),
                ('Quantity', models.PositiveIntegerField(max_length=150)),
                ('StockAvailableQuantity', models.PositiveIntegerField(max_length=150)),
                ('StockAvailableYesNo', models.CharField(max_length=50)),
                ('Price', models.PositiveIntegerField(max_length=50)),
            ],
        ),
    ]
